### ISSUE TITLE
Starting in on some edits

### ISSUE THREAD

**Issue by andyclymer** [LettError/robofabbook#1]
Hey!

I just started in on some edits to the RoboFab Print book page, it's all checked in on the "update-2017" branch.

It's been a few years now since 2009 and a lot has changed, but this book is still such a great resource for students who wish to continue on with more RoboFab examples after the small number of class sessions that I'm able to offer them. Even though things change and a designer is really interacting with DoodleFont objects, the RoboFab API still lives on, and I like the idea of editing the document to just be more API-specific.

With that in mind, I made edits to the documentation like so:

— I removed the individual documentation pages, centering everything around the single page "Print" edition 
— I removed some code examples that were specific to FontLab and that generally don't follow the RoboFab API
— I tried to make the document read in a more editor-agnostic way, though many example still do call out FontLab by name
— A couple examples that no longer work were removed (font.info.autoNaming(), etc.)

So that's a start. Next I'd like to have a section that points readers in a better way to the editor-specific documentation on RoboFont's and Glyph's sites as a resource to continue on from where this API introduction leaves off.

Erik, I have one request for you, would you consider setting up the index.html on this "update-2017" branch as a Github Page? That way I can link students directly to this living document. It looks like you need admin access to make this change.

Any comments?
Andy

**Comment by typemytype** [comment]
I would not spend to much time anymore on robofab... having this document working for fontParts would be nice.

**Comment by andyclymer** [comment]
I think so too. I wanted to bring this up-to-date for current students, but after that it's a great starting point for fontParts
